export const tasks = [
  {
    id: 1,
    title: "Complete project proposal",
    description: "Draft and finalize the project proposal for the new client",
    status: "In Progress",
    priority: "High",
    dueDate: "2023-06-30",
  },
  {
    id: 2,
    title: "Review code changes",
    description: "Go through the pull requests and provide feedback",
    status: "To Do",
    priority: "Medium",
    dueDate: "2023-06-25",
  },
  {
    id: 3,
    title: "Update documentation",
    description: "Revise and update the API documentation",
    status: "Done",
    priority: "Low",
    dueDate: "2023-06-20",
  },
  {
    id: 4,
    title: "Prepare for team meeting",
    description: "Gather progress reports and create presentation slides",
    status: "To Do",
    priority: "High",
    dueDate: "2023-06-28",
  },
  {
    id: 5,
    title: "Implement new feature",
    description: "Develop the new user authentication system",
    status: "In Progress",
    priority: "High",
    dueDate: "2023-07-05",
  },
  {
    id: 6,
    title: "Fix reported bugs",
    description: "Address and resolve the bugs reported in the latest release",
    status: "To Do",
    priority: "Medium",
    dueDate: "2023-06-29",
  },
  {
    id: 7,
    title: "Conduct user testing",
    description: "Organize and oversee user testing sessions for the new UI",
    status: "To Do",
    priority: "High",
    dueDate: "2023-07-10",
  },
  {
    id: 8,
    title: "Optimize database queries",
    description: "Improve the performance of slow database queries",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2023-07-03",
  },
  {
    id: 9,
    title: "Create marketing materials",
    description: "Design and produce marketing materials for the product launch",
    status: "To Do",
    priority: "Low",
    dueDate: "2023-07-15",
  },
  {
    id: 10,
    title: "Perform security audit",
    description: "Conduct a comprehensive security audit of the system",
    status: "To Do",
    priority: "High",
    dueDate: "2023-07-20",
  },
  {
    id: 11,
    title: "Refactor legacy code",
    description: "Modernize and improve the structure of the legacy codebase",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2023-07-25",
  },
  {
    id: 12,
    title: "Write unit tests",
    description: "Increase test coverage by writing additional unit tests",
    status: "To Do",
    priority: "Low",
    dueDate: "2023-07-08",
  },
];

